# Generated by Django 3.0.2 on 2020-02-02 04:56

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hcontent', tinymce.models.HTMLField()),
            ],
        ),
    ]
